# -*- coding: utf-8 -*-
"""milestone3 (app.py).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Si0lhgUajkC1Xww86Q1_ABq1-zOEDGjY
"""

pip install streamlit pandas plotly

# ===============================
# Milestone 3 – Crypto Risk Dashboard
# ===============================

import streamlit as st
import pandas as pd
import plotly.express as px

# -------------------------------
# Page Config
# -------------------------------
st.set_page_config(
    page_title="Crypto Risk & Volatility Dashboard",
    layout="wide"
)

st.title("📊 Crypto Risk & Volatility Analysis Dashboard")
st.markdown("### Interactive analysis of cryptocurrency risk & return")

# -------------------------------
# Load Data
# -------------------------------
@st.cache_data
def load_data():
    df = pd.read_csv("crypto_processed.csv")
    df["Date"] = pd.to_datetime(df["Date"])
    return df

df = load_data()

# -------------------------------
# Sidebar Filters
# -------------------------------
st.sidebar.header("🔍 Filters")

crypto_list = df["Crypto"].unique().tolist()
selected_crypto = st.sidebar.multiselect(
    "Select Cryptocurrencies",
    options=crypto_list,
    default=crypto_list
)

min_date = df["Date"].min()
max_date = df["Date"].max()

date_range = st.sidebar.date_input(
    "Select Date Range",
    [min_date, max_date]
)

# Filter data
filtered_df = df[
    (df["Crypto"].isin(selected_crypto)) &
    (df["Date"] >= pd.to_datetime(date_range[0])) &
    (df["Date"] <= pd.to_datetime(date_range[1]))
]

# -------------------------------
# KPI Metrics
# -------------------------------
st.subheader("📌 Key Performance Indicators")

col1, col2, col3 = st.columns(3)

col1.metric(
    "Average Volatility",
    round(filtered_df["Volatility"].mean(), 4)
)

col2.metric(
    "Average Return",
    round(filtered_df["Returns"].mean(), 4)
)

col3.metric(
    "Average Sharpe Ratio",
    round(filtered_df["Sharpe_Ratio"].mean(), 4)
)

# -------------------------------
# Price Trend Graph
# -------------------------------
st.subheader("📈 Price Trend Over Time")

price_fig = px.line(
    filtered_df,
    x="Date",
    y="Close",
    color="Crypto",
    title="Crypto Price Movement"
)
st.plotly_chart(price_fig, use_container_width=True)

# -------------------------------
# Volatility Trend Graph
# -------------------------------
st.subheader("📉 Volatility Trend Over Time")

vol_fig = px.line(
    filtered_df,
    x="Date",
    y="Volatility",
    color="Crypto",
    title="Crypto Volatility Trend"
)
st.plotly_chart(vol_fig, use_container_width=True)

# -------------------------------
# Risk vs Return Scatter Plot
# -------------------------------

# Create Risk vs Return Scatter Plot (FIXED)
risk_return = (
    filtered_df.groupby("Crypto")
    .agg({
        "Volatility": "mean",
        "Returns": "mean"
    })
    .reset_index()
)

risk_return["Abs_Return"] = risk_return["Returns"].abs()

scatter_fig = px.scatter(
    risk_return,
    x="Volatility",
    y="Returns",
    size="Abs_Return",   # FIXED HERE
    color="Crypto",
    title="Risk vs Return Analysis",
    labels={
        "Volatility": "Risk (Volatility)",
        "Returns": "Average Return"
    }
)

st.plotly_chart(scatter_fig, use_container_width=True)

import pandas as pd
import plotly.express as px

# Example dataframe (replace with your filtered_df)
risk_return = filtered_df.groupby("Crypto").agg({
    "Volatility": "mean",
    "Returns": "mean"
}).reset_index()

# Fix for negative size
risk_return["Abs_Return"] = risk_return["Returns"].abs()

# Create plot
fig = px.scatter(
    risk_return,
    x="Volatility",
    y="Returns",
    size="Abs_Return",
    color="Crypto",
    title="Risk vs Return Analysis",
    labels={
        "Volatility": "Risk (Volatility)",
        "Returns": "Average Return"
    }
)

# SHOW IN COLAB
fig.show()